name: test_ubuntu

on:
  push:
    branches:
      - dev
      - public
    paths:
      - 'otimapp/**'
      - 'tests/**'
      - 'app.cpp'
      - '.github/workflows/test-ubuntu.yml'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: actions/checkout@v2
        with:
          repository: google/googletest
          path: third_party/googletest

      - uses: actions/checkout@v2
        with:
          repository: Kei18/grid-pathfinding
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: third_party/grid-pathfinding

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: test
        working-directory: build
        run: ./test

      - name: run-app
        working-directory: build
        run: |
          ./app -i ../instances/sample.txt -s PrioritizedPlanning -o ./plan.txt -v -f 4
          ./exec -i ../instances/sample.txt -p ./plan.txt -o ./exec.txt -v -u 0.5
