name: test_macos

on:
  push:
    branches:
      - dev
      - public
    paths:
      - 'mapf/**'
      - 'tests/**'
      - 'app.cpp'
      - '.github/workflows/test-macos.yml'

jobs:
  test-macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: actions/checkout@v2
        with:
          repository: google/googletest
          path: third_party/googletest

      - uses: actions/checkout@v2
        with:
          repository: Kei18/grid-pathfinding
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: third_party/grid-pathfinding

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: test
        working-directory: build
        run: ./test
