name: test_macos

on:
  push:
    branches:
      - dev
      - public
      - ijcai22
    paths:
      - 'otimapp/**'
      - 'tests/**'
      - 'app.cpp'
      - '.github/workflows/test-macos.yml'

jobs:
  test-macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: actions/checkout@v2
        with:
          repository: google/googletest
          path: third_party/googletest

      - uses: actions/checkout@v2
        with:
          repository: Kei18/grid-pathfinding
          path: third_party/grid-pathfinding

      - name: build
        run: cmake -B build && make -C build

      - name: test
        working-directory: build
        run: ./test

      - name: run-app
        working-directory: build
        run: |
          ./app -i ../sample-instance.txt -s PP -o ./plan.txt -v
          ./exec -i ../sample-instance.txt -p ./plan.txt -o ./exec.txt -v -u 0.5
